/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Office } from "./Office";
import { OfficeCountArgs } from "./OfficeCountArgs";
import { OfficeFindManyArgs } from "./OfficeFindManyArgs";
import { OfficeFindUniqueArgs } from "./OfficeFindUniqueArgs";
import { CreateOfficeArgs } from "./CreateOfficeArgs";
import { UpdateOfficeArgs } from "./UpdateOfficeArgs";
import { DeleteOfficeArgs } from "./DeleteOfficeArgs";
import { ServiceAgentFindManyArgs } from "../../serviceAgent/base/ServiceAgentFindManyArgs";
import { ServiceAgent } from "../../serviceAgent/base/ServiceAgent";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { OfficeService } from "../office.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Office)
export class OfficeResolverBase {
  constructor(
    protected readonly service: OfficeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "read",
    possession: "any",
  })
  async _officesMeta(
    @graphql.Args() args: OfficeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Office])
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "read",
    possession: "any",
  })
  async offices(@graphql.Args() args: OfficeFindManyArgs): Promise<Office[]> {
    return this.service.offices(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Office, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "read",
    possession: "own",
  })
  async office(
    @graphql.Args() args: OfficeFindUniqueArgs
  ): Promise<Office | null> {
    const result = await this.service.office(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Office)
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "create",
    possession: "any",
  })
  async createOffice(@graphql.Args() args: CreateOfficeArgs): Promise<Office> {
    return await this.service.createOffice({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Office)
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "update",
    possession: "any",
  })
  async updateOffice(
    @graphql.Args() args: UpdateOfficeArgs
  ): Promise<Office | null> {
    try {
      return await this.service.updateOffice({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Office)
  @nestAccessControl.UseRoles({
    resource: "Office",
    action: "delete",
    possession: "any",
  })
  async deleteOffice(
    @graphql.Args() args: DeleteOfficeArgs
  ): Promise<Office | null> {
    try {
      return await this.service.deleteOffice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ServiceAgent], { name: "serviceAgents" })
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "read",
    possession: "any",
  })
  async findServiceAgents(
    @graphql.Parent() parent: Office,
    @graphql.Args() args: ServiceAgentFindManyArgs
  ): Promise<ServiceAgent[]> {
    const results = await this.service.findServiceAgents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User], { name: "users" })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async findUsers(
    @graphql.Parent() parent: Office,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
