/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerQueueService } from "../customerQueue.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerQueueCreateInput } from "./CustomerQueueCreateInput";
import { CustomerQueue } from "./CustomerQueue";
import { CustomerQueueFindManyArgs } from "./CustomerQueueFindManyArgs";
import { CustomerQueueWhereUniqueInput } from "./CustomerQueueWhereUniqueInput";
import { CustomerQueueUpdateInput } from "./CustomerQueueUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerQueueControllerBase {
  constructor(
    protected readonly service: CustomerQueueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerQueue })
  @nestAccessControl.UseRoles({
    resource: "CustomerQueue",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerQueue(
    @common.Body() data: CustomerQueueCreateInput
  ): Promise<CustomerQueue> {
    return await this.service.createCustomerQueue({
      data: data,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        queueNumber: true,
        serviceType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerQueue] })
  @ApiNestedQuery(CustomerQueueFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerQueue",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerQueues(
    @common.Req() request: Request
  ): Promise<CustomerQueue[]> {
    const args = plainToClass(CustomerQueueFindManyArgs, request.query);
    return this.service.customerQueues({
      ...args,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        queueNumber: true,
        serviceType: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerQueue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerQueue",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerQueue(
    @common.Param() params: CustomerQueueWhereUniqueInput
  ): Promise<CustomerQueue | null> {
    const result = await this.service.customerQueue({
      where: params,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        queueNumber: true,
        serviceType: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerQueue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerQueue",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerQueue(
    @common.Param() params: CustomerQueueWhereUniqueInput,
    @common.Body() data: CustomerQueueUpdateInput
  ): Promise<CustomerQueue | null> {
    try {
      return await this.service.updateCustomerQueue({
        where: params,
        data: data,
        select: {
          createdAt: true,
          duration: true,
          id: true,
          queueNumber: true,
          serviceType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerQueue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerQueue",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerQueue(
    @common.Param() params: CustomerQueueWhereUniqueInput
  ): Promise<CustomerQueue | null> {
    try {
      return await this.service.deleteCustomerQueue({
        where: params,
        select: {
          createdAt: true,
          duration: true,
          id: true,
          queueNumber: true,
          serviceType: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
