/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceAgentService } from "../serviceAgent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceAgentCreateInput } from "./ServiceAgentCreateInput";
import { ServiceAgent } from "./ServiceAgent";
import { ServiceAgentFindManyArgs } from "./ServiceAgentFindManyArgs";
import { ServiceAgentWhereUniqueInput } from "./ServiceAgentWhereUniqueInput";
import { ServiceAgentUpdateInput } from "./ServiceAgentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceAgentControllerBase {
  constructor(
    protected readonly service: ServiceAgentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceAgent })
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceAgent(
    @common.Body() data: ServiceAgentCreateInput
  ): Promise<ServiceAgent> {
    return await this.service.createServiceAgent({
      data: {
        ...data,

        office: data.office
          ? {
              connect: data.office,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceAgent] })
  @ApiNestedQuery(ServiceAgentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceAgents(@common.Req() request: Request): Promise<ServiceAgent[]> {
    const args = plainToClass(ServiceAgentFindManyArgs, request.query);
    return this.service.serviceAgents({
      ...args,
      select: {
        createdAt: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceAgent(
    @common.Param() params: ServiceAgentWhereUniqueInput
  ): Promise<ServiceAgent | null> {
    const result = await this.service.serviceAgent({
      where: params,
      select: {
        createdAt: true,
        id: true,

        office: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceAgent(
    @common.Param() params: ServiceAgentWhereUniqueInput,
    @common.Body() data: ServiceAgentUpdateInput
  ): Promise<ServiceAgent | null> {
    try {
      return await this.service.updateServiceAgent({
        where: params,
        data: {
          ...data,

          office: data.office
            ? {
                connect: data.office,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          office: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceAgent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceAgent(
    @common.Param() params: ServiceAgentWhereUniqueInput
  ): Promise<ServiceAgent | null> {
    try {
      return await this.service.deleteServiceAgent({
        where: params,
        select: {
          createdAt: true,
          id: true,

          office: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
